# Generated by Django 2.2.9 on 2020-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(max_length=30, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(max_length=30, verbose_name='病院名'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='introduction_text',
            field=models.TextField(max_length=1000, verbose_name='紹介文'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(default='defo', upload_to='documents/', verbose_name='画像'),
        ),
    ]
