# Generated by Django 2.2.9 on 2021-01-31 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201119_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DoctorReservationReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)], verbose_name='曜日')),
                ('frequency', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)], verbose_name='頻度')),
                ('start_day', models.DateField(blank=True, null=True, verbose_name='受付開始日')),
                ('end_day', models.DateField(blank=True, null=True, verbose_name='受付終了日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='受付開始時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='受付終了時間')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Doctor')),
            ],
        ),
    ]
