# Generated by Django 2.2.9 on 2020-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('hospital_name', models.CharField(max_length=30)),
                ('introduction_text', models.TextField(max_length=1000)),
                ('profile_image', models.ImageField(default='defo', upload_to='documents/')),
            ],
        ),
    ]
